#request
geometry_msgs/Pose pose #Goal Pose of End Effector
string base_frame #Frame of the Coordinates
float64 max_velocity_scaling_factor
float64 max_acceleration_scaling_factor
bool[3] use_force
bool[3] use_torque
float64[3] force_thresholds
float64[3] torque_thresholds
---

#response
geometry_msgs/Pose pose
float64[3] force
float64[3] torque